export const blogList = [
  {
    id: 1,
    title: "7 CSS tools you should be using ",
    category: "development",
    subCategory: ["frontend", "ui/ux", "design"],
    description:
      "CSS is getting more and more complicated to write. Thankfully, there are tools that make the task of authoring CSS a little bit easier. From identifying errors in your stylesheets to presenting useful stats about your code, these online tools will undoubtedly help during CSS development.",
    authorName: "Hancer Mercede",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "August 04, 2023",
    cover: "/assets/images/designer-1.jpg",
  },
  {
    id: 2,
    title: "Milan Places That Highlight The City",
    category: "travel",
    subCategory: ["vacation", "holidays", "sight seeing"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "Max Stevens",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 12, 2023",
    cover: "/assets/images/f67396fc3cfce63a28e07ebb35d974ac.jpg",
  },
  {
    id: 3,
    title: "Online Shopping – An Alternative to Shopping in the Mall",
    category: "shopping",
    subCategory: ["e-commerce store", "clothing", "shopping store"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/fQwuyKJ9qxjSbr6REcgtmW-1200-80.jpg",
  },
  {
    id: 4,
    title: "ADVENTURE IN YOU",
    category: "adventure",
    subCategory: ["adrenaline", "stay-fit", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/graphic-design-trends.png",
  },
  {
    id: 5,
    title: "Loaded BBQ Baked Potatoes",
    category: "cooking",
    subCategory: ["bbq", "food", "lifestyle"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
  },
  {
    id: 6,
    title: "Beyond the Beach",
    category: "travel",
    subCategory: ["beaches", "sea", "holidays"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover:
      "/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg",
  },
  {
    id: 7,
    title: "Art & Perception",
    category: "art",
    subCategory: ["skill", "design", "passion"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "John Doe",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/Synthwave-Postmodern.jpg",
  },
  {
    id: 8,
    title: "Node.js Back-End Development",
    category: "Development",
    subCategory: ["Back-End", "Front-End", "Full-Stack"],
    description:
      "Node.js is a framework for use js in the back-end, with Node.js you can build modern web apps, RESTful APIs, mobile apps, and more, this is a advantage for developers because they don't have to know other language to write code.",
    authorName: "Hancer Mercede",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 27, 2023",
    cover: "/assets/images/Synthwave-Postmodern-3.jpg",
  },
  {
    id: 9,
    title: "MariaDB: A Powerful Data Base",
    category: "Development",
    subCategory: ["Back-End", "Data Bases", "Persistence"],
    description:
      "MariaDB is a community-developed, commercially supported fork of the MySQL relational database management system (RDBMS), intended to remain free and open-source software under the GNU General Public License.",
    authorName: "Thomas Anderson",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "June 31, 2023",
    cover: "/assets/images/CiberCity.jpg",
  },
  {
    id: 10,
    title: "React.js your best choice.",
    category: "Development",
    subCategory: ["Front-End", "Development", "Full-Stack"],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: "Hancer Mercede",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "August 05, 2023",
    cover: "/assets/images/React.jpg",
  },
];
